### PR TITLE
Feature: Tracking Events

### PR DESCRIPTION
**Pull request by daniellealexis**
Added function for tracking so in case we want to change how we do it in the future, its easily updateable. Added event tracking for clicking the call button, and clicking social sharing

### CODE REVIEW

**Review by lachlanjc — APPROVED** [review]
Looks great!

**Comment by stewartjks** [comment]
Agreed -- looks great, Dani!

**Comment by stewartjks** [comment]
Darn, doesn't look like this is working yet. We're not showing any events reported in Google Analytics. I don't see any fire when I run a Tag Assistant recording

[tag_log.pdf](https://github.com/lachlanjc/calltoaction/files/653875/tag_log.pdf)

**Comment by daniellealexis** [comment]
I don't know if it's been deployed yet. @Mitul?

**Pull request merged**
